language: python

install:
  - sudo apt-get update
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install busted

before_script:
  - busted --version

script:
  - busted --output=TAP

notifications:
  recipients:
    - arne@twobeer.de
  email:
    on_failure: always
